name: e_commerce
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^1.0.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  google_fonts: ^2.1.0

flutter_icons:
  image_path: "assets/icon/launch_image.png"
  android: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - assets/wheat.png
    - assets/random_crop.png
    - assets/maize.png
    - assets/harvester.png
    - assets/cats/tshirt.png
    - assets/cats/accessories.png
    - assets/cats/dress.png
    - assets/cats/formal.png
    - assets/cats/informal.png
    - assets/cats/jeans.png
    - assets/cats/shoe.png
    - assets/products/blazer1.jpeg
    - assets/products/dress1.jpeg
    - assets/products/dress2.jpeg
    - assets/products/hills1.jpeg
    - assets/products/hills2.jpeg
    - assets/products/pants2.jpeg
    - assets/products/skt1.jpeg
    - assets/products/skt2.jpeg
    - assets/products/blazer2.jpeg
    - assets/final_welcome.png
    - assets/crop_guide/bajra.png
    - assets/crop_guide/groundnut.png
    - assets/crop_guide/moong.png
    - assets/crop_guide/pea.png
    - assets/crop_guide/potato.png
    - assets/crop_guide/rice.png
    - assets/crop_guide/soyabean.png
    - assets/crop_guide/tobacco.png
    - assets/crop_guide/tur.png
    - assets/crop_guide/wheat.png
    - assets/fertilizer_ad_1.png
    - assets/fertilizer_ad_2.png
    - assets/fertilizer_Ad_3.png
    - assets/fertilizer_ad_4.png
    - assets/crop_guide_ad_2.png
    - assets/crop_guide_ad_3.png
    - assets/crop_guide_ad_4.png
    - assets/products/Green Drop Rs.600.png
    - assets/products/N . p . k Sulphur Enriched 92.kg.png
    - assets/products/Nature Plus bio farm 55.kg.png
    - assets/products/Neem Khali 1kg Rs.62.png
    - assets/products/organic manure 1kg 195.png
    - assets/products/Plant Nutrient Rs.195.png
    - assets/products/Ready to pot Rs.50 1kg.png
    - assets/products/Urea Neem Coated Rs.130 1kg.png
    - assets/products/Vermi Compost Rs.60 1kg.png
    - assets/products/ashish 1 moong.png
    - assets/products/ashish 2 soyabean.png
    - assets/products/ashish 3 tur .png
    - assets/products/ashish 4 potato.png
    - assets/products/ashish 5 bajra .png
    - assets/products/ashish 6 rice.png
    - assets/products/ashish 7 wheat.png
    - assets/products/ashish 8 tobacco.png
    - assets/products/ashish 9 pea.png
    - assets/products/ashish 10 groundnut.png
    - assets/welcome_final_1.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
